#!/bin/bash
# Build initial database

DBINIT=$OPENSHIFT_REPO_DIR/WaDE_Sept2014_Postgres

cd $DBINIT

# Create custom schemas
psql -d $OPENSHIFT_APP_NAME -f install.sql > install.log

# Restore DB
pg_restore -d $OPENSHIFT_APP_NAME WaDE_Postgres_Sept2014.backup > restore.log


